fplot(@(x) .65*cos(4*x*pi/180),[0 6], LineWidth=2)
ylim([0 1])
xlabel('Gradient \theta (Degrees)')
ylabel('T^E_1')
title('Center-Pivot Water Efficiency vs. Land Slope')
fplot(@(x) .75*cos(x*pi/180),[0 6], LineWidth=2)
ylim([0 1])
xlabel('Gradient \theta (Degrees)')
ylabel('T^E_2')
title('Sprinkler Water Efficiency vs. Land Slope')
 
% fplot(@(x) .9,[0 6], LineWidth=2)
ylim([0 1])
xlabel('Gradient \theta (Degrees)')
ylabel('T^E_3')
title('Drip Water Efficiency vs. Land Slope')
fplot(@(x) (2.92*(x+.558)^3)/(exp(2.27*(x+.558))-1)+.25,[0 6], LineWidth=2)
ylim([0 1])
xlabel('Gradient \theta (Degrees)')
ylabel('T^E_4')
title('Furrow Water Efficiency vs. Land Slope')